const ADMIN_EMAIL = "contact@phrazs.com";
const ADMIN_PASSCODE = "phrazs-owner-2026";

window.PHRAZS_DATA = {
  source: {
    site: "https://phrazs.com/",
    extractedOn: "2026-05-29",
    notes: [
      "Data was extracted from public Phrazs pages: home, properties, paginated property archives, blog, contact, terms, host pages, and listing detail snippets.",
      "Images are referenced from the public Phrazs media library instead of duplicated locally.",
      "The admin gate is client-side for this static rebuild. Use real server auth before accepting private data or payments."
    ]
  },
  brand: {
    name: "Phrazs",
    tagline: "Find your setting",
    description: "Handpicked houses, apartments and rooms for short-term rent.",
    logo: "https://phrazs.com/wp-content/uploads/2023/12/cropped-site_logo.png",
    heroImage: "https://phrazs.com/wp-content/uploads/2025/12/home-slider-1.jpeg",
    email: "contact@phrazs.com",
    legalAddress: "_, Atlanta, GA, United States"
  },
  categories: [
    {
      name: "Commercial",
      count: 6,
      description: "Spacious and inviting settings ideal for family gatherings, lifestyle shoots, holiday celebrations, and intimate events.",
      image: "https://phrazs.com/wp-content/uploads/2025/10/color-400x300.jpeg"
    },
    {
      name: "Outdoor",
      count: 0,
      description: "Refreshing poolside locations great for seasonal campaigns, influencer projects, music shoots, and luxury lifestyle shoots.",
      image: "https://phrazs.com/wp-content/uploads/2021/09/image-4-400x300.jpg"
    },
    {
      name: "Backyards",
      count: 0,
      description: "Private outdoor spaces for creative workshops, fashion shoots, small events, and ambient storytelling.",
      image: "https://phrazs.com/wp-content/uploads/2021/09/image-14-400x300.jpg"
    },
    {
      name: "Residential",
      count: 11,
      description: "Chic spaces perfect for urban stories, influencer content, product shoots, and casual gatherings.",
      image: "https://phrazs.com/wp-content/uploads/2021/09/image-11-400x300.jpg"
    }
  ],
  tags: ["Kitchen", "Wedding Halls", "Music Video", "Rooftop", "Parking Garage", "Film Shoot", "Birthday Party", "Backyard", "Tiny Homes", "Photo Studios", "Ranches", "Podcast", "Studio Shoot", "Interview Shoot"],
  listings: [
    {
      id: "podcast-sparq-social",
      title: "Podcast at SparQ Social",
      category: "Commercial",
      url: "https://phrazs.com/listing/podcast-at-sparq-social/",
      image: "https://phrazs.com/wp-content/uploads/2025/09/Capture-13-400x300.jpg",
      added: "September 23, 2025",
      sqft: 160,
      crew: 7,
      hours: 10,
      pets: "Not Allowed",
      price: 75,
      priceLabel: "$75.00",
      rating: 0,
      reviews: 0,
      checkIn: "After 10:00 am",
      checkOut: "Before 10:00 pm",
      tags: ["Film Shoot", "Interview Shoot", "Podcast"],
      host: "Dre Manning",
      description: "A professional podcast space with sound-treated recording, Rode microphones, a Zoom PodTrak P8 mixer, audio engineer support, prep area, snacks, beverages, and ample parking.",
      amenities: ["Lighting Equipment", "Wardrobe Rack", "WiFi"],
      features: ["Restrooms", "Wheelchair Accessible", "Soundproof", "Parking Space(s)"],
      rules: ["No smoking, vapes, e-cigarettes, or hookah pens.", "No heavy alcohol; wine is fine.", "Outside catering is allowed with cleanup required.", "Security cameras record throughout the studio."]
    },
    {
      id: "go-bold-studio",
      title: "Go Bold Studio",
      category: "Commercial",
      url: "https://phrazs.com/listing/go-bold-studio/",
      image: "https://phrazs.com/wp-content/uploads/2025/10/color-400x300.jpeg",
      added: "October 8, 2025",
      sqft: 2200,
      crew: 20,
      hours: 20,
      pets: "Allowed",
      price: 600,
      priceLabel: "$600.00",
      rating: 0,
      reviews: 0,
      checkIn: "After 6:00 am",
      checkOut: "Before 10:00 pm",
      tags: ["Backdrop", "Film Shoot", "Indoors", "Music Video", "Photo Studios", "Studio Shoot"],
      host: "Go Bold Studio",
      description: "A Central Florida studio with a 25x25 cyc wall, professional lighting, modern technology, and a 300 sq. ft. flex room for lounge, wardrobe, makeup, or extra shooting needs.",
      amenities: ["4x Arri S60 Cyc Lighting", "Grip Cart Package", "3x Stage Flats", "4x Folding Tables", "8x Folding Chairs", "Speakers", "Projector", "WiFi", "300-sf Conference Room", "Prep Area", "Restroom", "85-inch Sony Bravia 4K HDR"],
      features: ["Street level access", "Parking Space(s)"],
      rules: ["Do not walk on the curve portion of the cyc wall.", "No candles, fires, smoking, vaping, alcohol, illegal substances, adult shoots, or stunts.", "Setup and teardown must happen during rental time.", "Maximum occupancy is 20 persons."]
    },
    {
      id: "modex-studio",
      title: "MODEx Studio",
      category: "Commercial",
      url: "https://phrazs.com/listing/modex-studio/",
      image: "https://phrazs.com/wp-content/uploads/2026/05/DSC06014-400x300.jpg",
      added: "May 9, 2026",
      sqft: 4000,
      crew: 150,
      hours: 12,
      pets: "Not Allowed",
      price: 250,
      priceLabel: "$250.00",
      rating: 0,
      reviews: 0,
      tags: ["Film Shoot", "Music Video", "Photo Studios"],
      host: "Phrazs host",
      description: "Large commercial creative studio listing from the public catalog.",
      amenities: [],
      features: []
    },
    {
      id: "vintage-1930s-school",
      title: "Vintage 1930's School Building",
      category: "Commercial",
      url: "https://phrazs.com/listing/vintage-1930s-school-building/",
      image: "https://phrazs.com/wp-content/uploads/2025/11/DSC06563-400x300.jpg",
      added: "November 17, 2025",
      sqft: 28000,
      crew: 100,
      hours: 24,
      pets: "Not Allowed",
      price: 150,
      priceLabel: "$150.00",
      rating: 0,
      reviews: 0,
      tags: ["Film Shoot", "Music Video"],
      host: "Phrazs host",
      description: "Vintage commercial school building from the public catalog.",
      amenities: [],
      features: []
    },
    {
      id: "studio-a-sparq",
      title: "Studio A | Big Mama's House at SparQ Social",
      category: "Commercial",
      url: "https://phrazs.com/listing/studio-a-big-mamas-house-at-sparq-social/",
      image: "https://phrazs.com/wp-content/uploads/2025/09/ADP02726-400x300.jpg",
      added: "September 1, 2025",
      sqft: 500,
      crew: 6,
      hours: 10,
      pets: "Not Allowed",
      price: 55,
      priceLabel: "$55.00",
      rating: 0,
      reviews: 0,
      tags: ["Film Shoot", "Interview Shoot", "Podcast"],
      host: "Dre Manning",
      description: "Studio A at SparQ Social from the public catalog.",
      amenities: [],
      features: []
    },
    {
      id: "new-remodeled-apartment",
      title: "New remodeled apartment",
      category: "Residential",
      url: "https://phrazs.com/listing/newly-remodeled-apartment/",
      image: "https://phrazs.com/wp-content/uploads/2021/09/image-11-400x300.jpg",
      added: "October 15, 2021",
      sqft: 800,
      crew: 6,
      hours: 7,
      pets: "Allowed",
      price: 139,
      priceLabel: "$139.00 / day",
      rating: 4.5,
      reviews: 2,
      tags: ["Kitchen", "Music Video"],
      host: "AKSHAT",
      description: "Remodeled apartment listed for day rental."
    },
    {
      id: "secluded-cozy-house-daily",
      title: "Secluded cozy house",
      category: "Residential",
      url: "https://phrazs.com/listing/modern-and-secluded-house-3/",
      image: "https://phrazs.com/wp-content/uploads/2021/09/image-10-400x300.jpg",
      added: "September 30, 2021",
      sqft: 950,
      crew: 5,
      hours: 3,
      pets: "Allowed",
      price: 300,
      priceLabel: "$300.00 / day",
      rating: 1.3,
      reviews: 3,
      tags: ["Backyard", "Film Shoot"],
      host: "AKSHAT",
      description: "Secluded cozy house with space for small productions."
    },
    {
      id: "secluded-cozy-house-commercial",
      title: "Secluded cozy house",
      category: "Commercial",
      url: "https://phrazs.com/listing/modern-and-secluded-house-2/",
      image: "https://phrazs.com/wp-content/uploads/2021/09/image-10-400x300.jpg",
      added: "September 30, 2021",
      sqft: 950,
      crew: null,
      hours: null,
      pets: "Allowed",
      price: 350,
      priceLabel: "$350.00",
      rating: 4.0,
      reviews: 2,
      tags: ["Film Shoot"],
      host: "AKSHAT",
      description: "Commercial version of the secluded cozy house listing."
    },
    {
      id: "cozy-central-studio-hourly",
      title: "Cozy central studio",
      category: "Residential",
      url: "https://phrazs.com/listing/cozy-central-studio-3/",
      image: "https://phrazs.com/wp-content/uploads/2021/09/image-9-400x300.jpg",
      added: "September 12, 2021",
      sqft: 500,
      crew: null,
      hours: null,
      pets: "Cats Only",
      price: 130,
      priceLabel: "$130.00 / day",
      rating: 5.0,
      reviews: 2,
      tags: ["Photo Studios"],
      host: "AKSHAT",
      description: "Cozy central studio from the residential catalog."
    },
    {
      id: "cozy-central-studio-residential",
      title: "Cozy central studio",
      category: "Residential",
      url: "https://phrazs.com/listing/cozy-central-studio-2/",
      image: "https://phrazs.com/wp-content/uploads/2021/09/image-9-400x300.jpg",
      added: "September 12, 2021",
      sqft: 500,
      crew: 3,
      hours: 8,
      pets: "Cats Only",
      price: 130,
      priceLabel: "$130.00",
      rating: 5.0,
      reviews: 2,
      tags: ["Photo Studios"],
      host: "AKSHAT",
      description: "Central studio with listed crew and hour capacity."
    },
    {
      id: "stunning-new-apartment",
      title: "Stunning new apartment",
      category: "Residential",
      url: "https://phrazs.com/listing/stunning-remodeled-apartment-3/",
      image: "https://phrazs.com/wp-content/uploads/2021/09/image-17-400x300.jpg",
      added: "September 12, 2021",
      sqft: 650,
      crew: null,
      hours: null,
      pets: "Cats Only",
      price: 150,
      priceLabel: "$150.00",
      rating: 3.5,
      reviews: 2,
      tags: ["Kitchen"],
      host: "Michelle",
      description: "Residential apartment listing from the public catalog."
    },
    {
      id: "new-spacious-house",
      title: "New spacious house",
      category: "Commercial",
      url: "https://phrazs.com/listing/beautiful-spacious-house-2/",
      image: "https://phrazs.com/wp-content/uploads/2021/09/image-8-400x300.jpg",
      added: "September 12, 2021",
      sqft: 950,
      crew: null,
      hours: null,
      pets: "Cats Only",
      price: 370,
      priceLabel: "$370.00",
      rating: 4.0,
      reviews: 2,
      tags: ["Film Shoot"],
      host: "AKSHAT",
      description: "Spacious commercial house from the public catalog."
    },
    {
      id: "room-sea-view-outdoor",
      title: "Room with a sea view",
      category: "Outdoor",
      url: "https://phrazs.com/listing/room-with-a-sea-view-2/",
      image: "https://phrazs.com/wp-content/uploads/2021/09/image-14-400x300.jpg",
      added: "September 12, 2021",
      sqft: 130,
      crew: 30,
      hours: 22,
      pets: "Not Allowed",
      price: 60,
      priceLabel: "$60.00 / day",
      rating: 4.0,
      reviews: 2,
      tags: ["Rooftop", "Music Video"],
      host: "AKSHAT",
      description: "Outdoor daily room listing with a sea view."
    },
    {
      id: "room-sea-view-residential",
      title: "Room with a sea view",
      category: "Residential",
      url: "https://phrazs.com/listing/room-with-a-sea-view/",
      image: "https://phrazs.com/wp-content/uploads/2021/09/image-14-400x300.jpg",
      added: "September 12, 2021",
      sqft: 130,
      crew: 10,
      hours: 16,
      pets: "Not Allowed",
      price: 60,
      priceLabel: "$60.00 / day",
      rating: 4.0,
      reviews: 2,
      tags: ["Rooftop", "Music Video"],
      host: "AKSHAT",
      description: "Residential daily room listing with a sea view."
    },
    {
      id: "seaside-house-pool",
      title: "Seaside house with a pool",
      category: "Commercial",
      url: "https://phrazs.com/listing/seaside-house-with-a-pool-3/",
      image: "https://phrazs.com/wp-content/uploads/2021/09/image-4-400x300.jpg",
      added: "September 11, 2021",
      sqft: 1800,
      crew: 5,
      hours: 5,
      pets: "Cats Only",
      price: 460,
      priceLabel: "$460.00",
      rating: 4.0,
      reviews: 2,
      tags: ["Backyard", "Rooftop"],
      host: "AKSHAT",
      description: "Commercial seaside house with a pool."
    },
    {
      id: "beautiful-central-room-outdoor",
      title: "Beautiful central room",
      category: "Outdoor",
      url: "https://phrazs.com/listing/beautiful-central-room/",
      image: "https://phrazs.com/wp-content/uploads/2021/09/image-16-400x300.jpg",
      added: "September 11, 2021",
      sqft: 120,
      crew: 34,
      hours: 24,
      pets: "Allowed",
      price: 70,
      priceLabel: "$70.00 / day",
      rating: 5.0,
      reviews: 2,
      tags: ["Birthday Party"],
      host: "AKSHAT",
      description: "Outdoor daily central room listing."
    },
    {
      id: "beautiful-central-room-residential",
      title: "Beautiful central room",
      category: "Residential",
      url: "https://phrazs.com/listing/beautiful-central-room-2/",
      image: "https://phrazs.com/wp-content/uploads/2021/09/image-16-400x300.jpg",
      added: "September 11, 2021",
      sqft: 120,
      crew: 5,
      hours: 12,
      pets: "Allowed",
      price: 70,
      priceLabel: "$70.00 / day",
      rating: 5.0,
      reviews: 2,
      tags: ["Birthday Party"],
      host: "AKSHAT",
      description: "Residential daily central room listing."
    },
    {
      id: "fully-furnished-studio",
      title: "Fully furnished studio",
      category: "Residential",
      url: "https://phrazs.com/listing/fully-furnished-studio/",
      image: "https://phrazs.com/wp-content/uploads/2021/09/image-19-400x300.jpg",
      added: "September 10, 2021",
      sqft: 370,
      crew: null,
      hours: null,
      pets: "Allowed",
      price: 120,
      priceLabel: "$120.00",
      rating: 4.5,
      reviews: 2,
      tags: ["Photo Studios"],
      host: "Michelle",
      description: "Fully furnished residential studio listing."
    },
    {
      id: "room-private-entrance",
      title: "Room with private entrance",
      category: "Rooms",
      url: "https://phrazs.com/listing/room-with-private-entrance/",
      image: "https://phrazs.com/wp-content/uploads/2021/09/image-15-400x300.jpg",
      added: "September 10, 2021",
      sqft: 150,
      crew: 1,
      hours: 1,
      pets: "Cats Only",
      price: 85,
      priceLabel: "$85.00 / day",
      rating: 4.5,
      reviews: 2,
      tags: ["Rooms"],
      host: "Michelle",
      description: "Private entrance room listing."
    },
    {
      id: "modern-seaside-studio",
      title: "Modern seaside studio",
      category: "Residential",
      url: "https://phrazs.com/listing/modern-seaside-studio-3/",
      image: "https://phrazs.com/wp-content/uploads/2021/09/image-12-400x300.jpg",
      added: "September 5, 2021",
      sqft: 450,
      crew: null,
      hours: null,
      pets: "Not Allowed",
      price: 145,
      priceLabel: "$145.00",
      rating: 4.5,
      reviews: 2,
      checkIn: "After 11:00 am",
      checkOut: "Before 2:00 pm",
      tags: ["Kitchen", "Music Video", "Rooftop"],
      host: "Michelle",
      description: "Modern seaside studio with reviews from Thomas and Brian on the public listing."
    },
    {
      id: "pet-friendly-apartment",
      title: "Pet friendly apartment",
      category: "Residential",
      url: "https://phrazs.com/listing/pet-friendly-apartment/",
      image: "https://phrazs.com/wp-content/uploads/2021/09/image-13-400x300.jpg",
      added: "September 2, 2021",
      sqft: 400,
      crew: null,
      hours: null,
      pets: "Allowed",
      price: 135,
      priceLabel: "$135.00",
      rating: 4.0,
      reviews: 2,
      tags: ["Kitchen"],
      host: "Michelle",
      description: "Residential pet friendly apartment listing."
    },
    {
      id: "stylish-remodeled-room",
      title: "Stylish remodeled room",
      category: "Rooms",
      url: "https://phrazs.com/listing/stylish-remodeled-room-2/",
      image: "https://phrazs.com/wp-content/uploads/2021/09/image-18-400x300.jpg",
      added: "September 1, 2021",
      sqft: 130,
      crew: null,
      hours: null,
      pets: "Cats Only",
      price: 50,
      priceLabel: "$50.00 / day",
      rating: 5.0,
      reviews: 2,
      tags: ["Rooms"],
      host: "Michelle",
      description: "Stylish remodeled room listing from the public catalog."
    }
  ],
  hosts: [
    { name: "JD 2", memberSince: "August 21, 2025", rating: null, reviews: 0, languages: [], services: [], listings: 0, image: "https://phrazs.com/wp-content/uploads/2023/12/cropped-site_logo-2-180x180.png" },
    { name: "AKSHAT", memberSince: "September 17, 2021", rating: 4.4, reviews: 12, languages: ["English"], services: ["City Tours", "Transfers"], listings: 28, image: "https://phrazs.com/wp-content/uploads/2023/12/image-1-1.jpg" },
    { name: "Michelle", memberSince: "September 15, 2021", rating: 4.3, reviews: 12, languages: ["English", "Spanish"], services: ["City Tours", "Transfers"], listings: 28, image: "https://phrazs.com/wp-content/uploads/2021/09/user-2.jpg" },
    { name: "Dre Manning", memberSince: "September 23, 2025", rating: null, reviews: 0, languages: [], services: [], listings: 2, image: "https://phrazs.com/wp-content/uploads/2025/09/ADP02726-400x300.jpg" }
  ],
  testimonials: [
    { quote: "Listing our extra room on Phrazs turned out to be the easiest side hustle ever. It is low effort, the platform handles everything, and we have met some lovely people too.", name: "Jason P.", role: "Frequent Traveler" },
    { quote: "I found the ideal backyard for my friend's birthday dinner thanks to Phrazs. It made it easy to choose the space and the host was incredibly welcoming and professional.", name: "Sandra Lockhart", role: "Frequent Traveler" },
    { quote: "Honestly, for the price, I did not expect the space to be this good. It was affordable, easy to book, and looked amazing on camera.", name: "Maggie Wallace", role: "Verified Host" }
  ],
  blog: [
    { title: "Hello world!", date: "June 13, 2023", author: "AKSHAT", categories: ["Uncategorized"], comments: "No Comments", image: "https://phrazs.com/wp-content/uploads/2023/12/cropped-site_logo.png" },
    { title: "Top 10 home decor ideas and useful tips", date: "September 30, 2021", author: "AKSHAT", categories: ["Ideas", "Tips"], comments: "3 Comments", image: "https://phrazs.com/wp-content/uploads/2021/09/image-3-400x300.jpg" },
    { title: "Top trends in minimalist interior design", date: "September 28, 2021", author: "AKSHAT", categories: ["Tips", "Trends"], comments: "No Comments", image: "https://phrazs.com/wp-content/uploads/2021/09/image-5-400x300.jpg" },
    { title: "Tips to pick better paint colors for your home", date: "September 26, 2021", author: "AKSHAT", categories: ["Ideas", "Tips"], comments: "No Comments", image: "https://phrazs.com/wp-content/uploads/2021/09/image-6-400x300.jpg" },
    { title: "A few modern home office design ideas", date: "September 24, 2021", author: "AKSHAT", categories: ["Ideas", "Trends"], comments: "No Comments", image: "https://phrazs.com/wp-content/uploads/2021/09/image-7-400x300.jpg" },
    { title: "How to decorate your living room for fall", date: "September 22, 2021", author: "AKSHAT", categories: ["Tips", "Trends"], comments: "No Comments", image: "https://phrazs.com/wp-content/uploads/2021/09/image-2-400x300.jpg" },
    { title: "Secret interior design tricks you should know", date: "September 20, 2021", author: "AKSHAT", categories: ["Ideas", "Trends"], comments: "No Comments", image: "https://phrazs.com/wp-content/uploads/2021/09/image-1-400x300.jpg" }
  ],
  inquiries: [
    { id: "lead-001", name: "Creative Producer", email: "producer@example.com", interest: "Go Bold Studio", status: "New", message: "Looking for a full-day cyc wall rental with parking." },
    { id: "lead-002", name: "Podcast Team", email: "podcast@example.com", interest: "Podcast at SparQ Social", status: "Reviewing", message: "Need a two-hour podcast block and audio engineer." },
    { id: "lead-003", name: "Event Planner", email: "events@example.com", interest: "Secluded cozy house", status: "New", message: "Checking pet rules and backyard availability." }
  ],
  users: [
    { id: "usr-001", name: "Creative Producer", email: "producer@example.com", role: "Guest", status: "Active", joined: "2026-05-01", bookings: 2, lifetimeValue: 1350 },
    { id: "usr-002", name: "Podcast Team", email: "podcast@example.com", role: "Guest", status: "Active", joined: "2026-05-08", bookings: 1, lifetimeValue: 150 },
    { id: "usr-003", name: "Dre Manning", email: "dre@example.com", role: "Host", status: "Active", joined: "2025-09-23", bookings: 6, lifetimeValue: 2280 },
    { id: "usr-004", name: "Go Bold Studio", email: "host@gobold.example.com", role: "Host", status: "Active", joined: "2025-10-08", bookings: 4, lifetimeValue: 4200 },
    { id: "usr-005", name: "Admin Owner", email: "contact@phrazs.com", role: "Admin", status: "Owner", joined: "2026-05-29", bookings: 0, lifetimeValue: 0 }
  ],
  bookingStructure: {
    statuses: ["Inquiry", "Pending Payment", "Confirmed", "Active", "Completed", "Cancelled", "Refund Requested"],
    bookingFields: ["Booking ID", "Guest", "Host", "Property", "Start", "End", "Crew Size", "Hours", "Subtotal", "Fees", "Host Payout", "Platform Fee", "Payment Status", "Booking Status"],
    paymentFields: ["Payment ID", "Booking ID", "Processor", "Method", "Card Brand", "Last 4", "Gross", "Fees", "Net", "Refunded", "Status", "Captured At"],
    calendarRules: ["Block unavailable host dates", "Prevent overlapping confirmed bookings", "Track pending holds separately", "Show active bookings on today's board", "Move finished bookings into completed history"]
  },
  bookings: [
    {
      id: "bk-1001",
      propertyId: "go-bold-studio",
      property: "Go Bold Studio",
      guest: "Creative Producer",
      guestEmail: "producer@example.com",
      host: "Go Bold Studio",
      start: "2026-06-04 09:00",
      end: "2026-06-04 17:00",
      date: "2026-06-04",
      hours: 8,
      crew: 12,
      status: "Active",
      paymentStatus: "Paid",
      subtotal: 1200,
      platformFee: 180,
      hostPayout: 1020,
      total: 1380,
      notes: "Full-day cyc wall shoot with parking and conference room."
    },
    {
      id: "bk-1002",
      propertyId: "podcast-sparq-social",
      property: "Podcast at SparQ Social",
      guest: "Podcast Team",
      guestEmail: "podcast@example.com",
      host: "Dre Manning",
      start: "2026-06-05 13:00",
      end: "2026-06-05 15:00",
      date: "2026-06-05",
      hours: 2,
      crew: 4,
      status: "Confirmed",
      paymentStatus: "Paid",
      subtotal: 150,
      platformFee: 22.5,
      hostPayout: 127.5,
      total: 172.5,
      notes: "Podcast block with audio engineer."
    },
    {
      id: "bk-1003",
      propertyId: "modex-studio",
      property: "MODEx Studio",
      guest: "Agency Scout",
      guestEmail: "agency@example.com",
      host: "Phrazs host",
      start: "2026-06-08 10:00",
      end: "2026-06-08 16:00",
      date: "2026-06-08",
      hours: 6,
      crew: 28,
      status: "Pending Payment",
      paymentStatus: "Awaiting Capture",
      subtotal: 1500,
      platformFee: 225,
      hostPayout: 1275,
      total: 1725,
      notes: "Large production hold. Payment not captured yet."
    },
    {
      id: "bk-0998",
      propertyId: "studio-a-sparq",
      property: "Studio A | Big Mama's House at SparQ Social",
      guest: "Music Producer",
      guestEmail: "music@example.com",
      host: "Dre Manning",
      start: "2026-05-21 11:00",
      end: "2026-05-21 15:00",
      date: "2026-05-21",
      hours: 4,
      crew: 5,
      status: "Completed",
      paymentStatus: "Paid Out",
      subtotal: 220,
      platformFee: 33,
      hostPayout: 187,
      total: 253,
      notes: "Completed studio session."
    },
    {
      id: "bk-0999",
      propertyId: "vintage-1930s-school",
      property: "Vintage 1930's School Building",
      guest: "Film Scout",
      guestEmail: "film@example.com",
      host: "Phrazs host",
      start: "2026-05-24 08:00",
      end: "2026-05-24 18:00",
      date: "2026-05-24",
      hours: 10,
      crew: 40,
      status: "Completed",
      paymentStatus: "Paid Out",
      subtotal: 1500,
      platformFee: 225,
      hostPayout: 1275,
      total: 1725,
      notes: "Completed location scout and shoot."
    }
  ],
  payments: [
    { id: "pay-9001", bookingId: "bk-1001", processor: "Stripe", method: "Card", cardBrand: "Visa", last4: "4242", gross: 1380, fees: 42.3, net: 1337.7, refunded: 0, status: "Captured", capturedAt: "2026-05-29 10:18" },
    { id: "pay-9002", bookingId: "bk-1002", processor: "Stripe", method: "Card", cardBrand: "Mastercard", last4: "4444", gross: 172.5, fees: 6.1, net: 166.4, refunded: 0, status: "Captured", capturedAt: "2026-05-29 11:04" },
    { id: "pay-9003", bookingId: "bk-1003", processor: "Stripe", method: "Card", cardBrand: "Amex", last4: "0005", gross: 1725, fees: 0, net: 0, refunded: 0, status: "Authorized", capturedAt: "Pending" },
    { id: "pay-8998", bookingId: "bk-0998", processor: "Stripe", method: "Card", cardBrand: "Visa", last4: "1881", gross: 253, fees: 8.12, net: 244.88, refunded: 0, status: "Paid Out", capturedAt: "2026-05-21 10:32" },
    { id: "pay-8999", bookingId: "bk-0999", processor: "Stripe", method: "Card", cardBrand: "Discover", last4: "1117", gross: 1725, fees: 51.75, net: 1673.25, refunded: 0, status: "Paid Out", capturedAt: "2026-05-24 07:42" }
  ],
  payouts: [
    { id: "po-7001", host: "Go Bold Studio", bookingId: "bk-1001", amount: 1020, status: "Scheduled", payoutDate: "2026-06-06" },
    { id: "po-7002", host: "Dre Manning", bookingId: "bk-1002", amount: 127.5, status: "Scheduled", payoutDate: "2026-06-07" },
    { id: "po-6998", host: "Dre Manning", bookingId: "bk-0998", amount: 187, status: "Completed", payoutDate: "2026-05-23" },
    { id: "po-6999", host: "Phrazs host", bookingId: "bk-0999", amount: 1275, status: "Completed", payoutDate: "2026-05-26" }
  ],
  calendar: [
    { date: "2026-06-04", property: "Go Bold Studio", status: "Booked", bookingId: "bk-1001", time: "09:00-17:00" },
    { date: "2026-06-05", property: "Podcast at SparQ Social", status: "Booked", bookingId: "bk-1002", time: "13:00-15:00" },
    { date: "2026-06-08", property: "MODEx Studio", status: "Hold", bookingId: "bk-1003", time: "10:00-16:00" },
    { date: "2026-06-10", property: "Vintage 1930's School Building", status: "Available", bookingId: "", time: "All day" },
    { date: "2026-06-11", property: "Studio A | Big Mama's House at SparQ Social", status: "Blocked", bookingId: "", time: "Maintenance" }
  ],
  legal: {
    termsUpdated: "12/22/24",
    company: "Phrazs",
    jurisdiction: "Georgia, United States",
    payments: ["Visa", "Mastercard", "American Express", "Discover"],
    refundPolicy: "All sales are final and no refund will be issued.",
    privacy: "The services are hosted in the United States and users consent to data transfer and processing in the United States."
  }
};
